version: '3'
services:

  nginx:
    build:
      context: ./nginx
    restart: unless-stopped
    ports:
      - "80:80"
      #- "443:443"

  mysql:
    build:
      context: ./mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: i_am_groot
      MYSQL_DATABASE: tron_light_cycles
      MYSQL_USER: tron
      MYSQL_PASSWORD: tron