version: "3"

services:
  nginx:
    build:
      context: ./nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "9090:9090"
      #- "443:443"
    links:
      - "gameserver"

  mysql:
    build:
      context: ./mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: i_am_groot
      MYSQL_DATABASE: tron_light_cycles
      MYSQL_USER: tron
      MYSQL_PASSWORD: tron

  node:
    build:
      context: ./node
    restart: unless-stopped
    ports:
      - "8080:8080"
    links:
      - "mysql"
    depends_on:
      - "mysql"
    environment:
      NODE_ENV: development
      MYSQL_HOST: mysql
      MYSQL_DATABASE: tron_light_cycles
      MYSQL_USER: tron
      MYSQL_PASSWORD: tron

  gameserver:
    build:
      context: ./gameserver
    restart: unless-stopped
    ports:
      - "9000:9000"