version: "3"

services:
  nginx:
    build:
      context: ./nginx
    restart: unless-stopped
    ports:
      - "80:80"
      #- "443:443"

  mysql:
    build:
      context: ./mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: i_am_groot
      MYSQL_DATABASE: tron_light_cycles
      MYSQL_USER: tron
      MYSQL_PASSWORD: tron

  node:
    build:
      context: ./node
    restart: unless-stopped
    ports:
      - "9091:9091"
    links:
      - "mysql"
    environment:
      DB_HOST: mysql
      DB_NAME: tron_light_cycles
      DB_USER: tron
      DB_PASS: tron
