name: Build and Test
 
on: [push, pull_request]
 
jobs:
  maven_java:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 12, 13 ]
    name: Build and test on ${{ matrix.java }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Maven clean compile
        run: mvn -f pom.xml clean compile
        working-directory: ./app
      - name: Maven test
        run: mvn test
        working-directory: ./app
  npm_react:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
     - name: Checkout
       uses: actions/checkout@v1
     - name: Setup Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v1
       with:
         node-version: ${{ matrix.node-version }}
     - name: npm install
       run: npm install
       working-directory: ./frontend/tron_ux
     - name: npm run build
       run: npm run build
       working-directory: ./frontend/tron_ux
     - name: npm test
       run: npm test
       working-directory: ./frontend/tron_ux
