name: Build and Test
 
on: [push, pull_request]
 
jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 12, 13 ]
    name: Java ${{ matrix.java }} compile
    steps:
      - uses: actions/checkout@develop
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - run: |
          cd app
          mvn -f github-actions-java-maven/pom.xml clean compile
          mvn test

