name: CI

on: [push, pull_request]

jobs:
  maven_java:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 12, 13 ]
    name: Maven build & test on java ${{ matrix.java }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Run maven clean compile
        run: mvn -f pom.xml clean compile
        working-directory: ./gameserver
      - name: Run maven test
        run: mvn test
        working-directory: ./gameserver
  npm_react:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    name: Npm build & test on node ${{ matrix.node-version }}
    steps:
     - name: Checkout repository
       uses: actions/checkout@v1
     - name: Setup Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v1
       with:
         node-version: ${{ matrix.node-version }}
     - name: Run npm install
       run: npm install
       working-directory: ./frontend/tron_ux
     - name: Run npm run build
       run: npm run build
       working-directory: ./frontend/tron_ux
     - name: Run npm test
       run: npm test
       env:
        CI: true
       working-directory: ./frontend/tron_ux
